EditHotel:
    type: input-object
    config:
        fields:
            id:
                type: "Int"
                description: "Hotel ID"
            name:
                type: "String"
                description: "Hotel name"
            address:
                type: "String"
                description: "Hotel address"
            website:
                type: "String"
                description: "Hotel website"