HotelCollection:
    type: object
    config:
        description: "Hotel list"
        fields:
            hotels:
                type: "[Hotel]"
                description: "hotels"
            pagingInfoResponse:
                type: "PagingInfoResponse"
                description: "Get Paging Info"
            errors:
                type: "String"
                description: "Hotel collection errors"