Query:
    type: object
    config:
        description: "Main query"
        fields:
            hotel:
                type: "Hotel"
                args:
                    id:
                        description: "Get Hotel by ID"
                        type: "Int"
                resolve: "@=resolver('Hotel', [args])"
            hotels_collection:
                type: "HotelCollection"
                args:
                    pagingInfo:
                        description: "Get pagingInfo"
                        type: "PagingInfo"
                    name:
                        description: "Get hotel by name"
                        type: "String"
                    address:
                        description: "Get hotel by address"
                        type: "String"
                    website:
                        description: "Get hotel by website"
                        type: "String"
                    sortInfo:
                        description: "Get sort Info"
                        type: "SortInfo"
                resolve: "@=resolver('HotelList', [args])"